pipeline {
    agent none
    stages {
        stage('Run app') {
            agent {
                docker { image 'kmaharwal1/python-pytest:latest' }
            }
            steps {
                dir('python-simple-app') {
                    sh 'python app.py'
                    sh 'pytest'
                }                   
            }
        }
        stage('Run tests') {
            agent {
                docker { image 'kmaharwal1/python-pytest:latest' }
            }
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q'
            }
        }
    }
}
