pipeline {
    agent { docker { image 'kmaharwal1/python-pytest:latest' } }
    stages {
            steps {
                dir('python-simple-app') {
                    sh 'python --version'
                    sh 'python app.py'
                }                   
            }
        }
        stage('Run tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q'
            }
        }
    }
}
